//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyExposure.Repository.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyExposure.Repository.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///	Welcome to the new blog of CurrencyExposure.com! &amp;nbsp;
        ///&lt;/div&gt;
        ///&lt;div&gt;
        ///	We started this blog because we have sold foreign currency solutions to the SME and Corporate segment in Australia and have a very good understanding of the problems that businesses have in managing their foreign currency exposure.&amp;nbsp;
        ///&lt;/div&gt;
        ///&lt;div&gt;
        ///	&amp;nbsp;
        ///&lt;/div&gt;
        ///&lt;div&gt;
        ///	We also know the way that FX providers make money off their clients. &amp;nbsp;I have ripped off my share of clients over the years&amp;hellip;Yes I hate to adm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlogArticle1 {
            get {
                return ResourceManager.GetString("BlogArticle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	For many CFO&amp;rsquo;s a corporate hedging policy is not existent and decisions about when to hedge and how much are loosely proscribed.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	However, having a formal and objective policy that is signed off by a board of Director&amp;rsquo;s can be very advantageous when questions are asked about FX losses!&amp;nbsp; The aim of this series of articles is to illustrate some commonly used hedging policies and the advantages of implementing.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	Developing a hedging policy or strategy can be time  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlogArticle2 {
            get {
                return ResourceManager.GetString("BlogArticle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	Forward Exchange Contracts (FEC) are by far the most commonly used instrument to hedge currency exposure globally.&amp;nbsp; According to the Bank of International Settlements, 44% of daily FX turnover is made up from FEC&amp;rsquo;s, versus spot 37%.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	The reason why they are so commonly used is because they are simple to understand and whilst they are a &amp;ldquo;contract&amp;rdquo; as such, they are also quite flexible &amp;ndash; you can pre-deliver or draw down on forwards as and when you need to use the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlogArticle3 {
            get {
                return ResourceManager.GetString("BlogArticle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	The concepts in this article are simple but amazingly misunderstood by most participants in currency markets because FX providers are reticent to explain in it any great detail how they make money from their clients.&amp;nbsp; Have you ever wondered why your bank or FX provider more often than do not display their rates on their website?&amp;nbsp; The aim of this article is to explain how market rates are calculated and passed on.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	The basis of the spot market is the interbank rate or in any other [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlogArticle4 {
            get {
                return ResourceManager.GetString("BlogArticle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	The team here at&amp;nbsp;&lt;a href=&quot;http://currencyexposure.com/&quot; target=&quot;_blank&quot;&gt;CurrencyExposure.com&lt;/a&gt;&amp;nbsp;are not adverse to the use of currency options in a hedging strategy.&amp;nbsp;&amp;nbsp;Options can be used effectively in conjunction with other products when taking a portfolio approach to hedge.&amp;nbsp;&amp;nbsp;However we are a cynical bunch over here and recommend that buyers beware - options are pushed hard by most FX providers because of the money they can make.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	There are an absolute pleth [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlogArticle5 {
            get {
                return ResourceManager.GetString("BlogArticle5", resourceCulture);
            }
        }
    }
}
